type Pizza {
  name: String!
  toppings: [String!]!
  nutritionalInfo: String
  price: Int
}

type Pasta {
  sauce: String
}

type Query {
  pizzas: [Pizza!]
  pasta(by_sauce: String): [Pasta!]
}

schema {
  query: Query
}
