[package]
name = "something-different-derive"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "^0.13.0"
proc-macro2 = "^0.3.0"
quote = "^0.5.1"
matchbox-codegen = { path = "../matchbox-codegen" }