[package]
name = "something-different-derive"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]

[lib]
proc-macro = true

[dependencies]
graphql-parser = "^0.2.0"
heck = "^0"
syn = "0.11.11"
proc-macro2 = "^0.3"
quote = "^0.5.1"
